export enum DeliveryStatus {
  ASSIGNED = 'ASSIGNED',
  NOTIFIED = 'NOTIFIED',
  ACCEPTED = 'ACCEPTED',
  PICKED = 'PICKED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
