export enum NotificationTopic {
  ALL_USERS = 'ALL_USERS',
  ALL_DRIVERS = 'ALL_DRIVERS',
  ALL_MERCHANTS = 'ALL_MERCHANTS',
  ALL_CUSTOMERS = 'ALL_CUSTOMERS',
  ALL_OFFICE_OWNERS = 'ALL_OFFICE_OWNERS',
  ALL_OFFERS = 'ALL_OFFERS',
  ALL_COUPONS = 'ALL_COUPONS',
}
