export enum ExternalProvider {
  UBER_EATS = 'UBER_EATS',
  TALABAT = 'TALABAT',
  DOORDASH = 'DOORDASH',
  DELIVEROO = 'DELIVEROO',
  JEHEZ = 'JEHEZ',
  HUNGERSTATION = 'HUNGERSTATION',
  UNKNOWN = 'UNKNOWN',
}
